### ISSUE TITLE
Objects are not in the same order as they were registered when GetAllInstances is called

### ISSUE THREAD

**Issue by feO2x** [seesharper/LightInject#369]
When calling `ServiceContainer.GetAllInstances`, LightInject 5.0.3 will not return the objects in the same order as they were registered with the container:

```csharp
// xunit and FluentAssertions are required for this example to run
public sealed class LightInjectDifferentOrderTests
{
    [Fact]
    public void OrderIsMixedUp()
    {
        var container = new ServiceContainer();
        container.Register<IFoo, A>("A")
                 .Register<IFoo, B>("B")
                 .Register<IFoo, C>("C");

        var instancesFromContainer = container.GetAllInstances<IFoo>();

        var expectedInstances = new IFoo[] { new A(), new B(), new C() };
        instancesFromContainer.Should().Equal(expectedInstances, (x, y) => x.GetType() == y.GetType());
    }
}

public interface IFoo { }

public class A : IFoo { }

public class B : IFoo { }

public class C : IFoo { }
```

![image](https://user-images.githubusercontent.com/7884158/28314313-5296d974-6bba-11e7-9a6c-cf389740e750.png)

I think this feature is paramount as otherwise the developer has to manually resolve the types in the correct order, which could increase the amount of code in the register phase dramatically.

I also thought that previous versions (< 5.0.0) of LightInject were not affected by this behavior? This should be the cause of https://github.com/aspnet/KestrelHttpServer/issues/1783

**Comment by seesharper** [comment]
Services are registered in a hash table and therefore the order of registration might differ from the order for which services are resolved. This is expected and by design. LightInject.Microsoft.DependencyInjection preserves the order if retrieved through the adapter. This is a requirement of the adapter. A solution to your problem might be to add an attribute to your service implementations (e.g. OrderAttribute) and sort the list accordingly.

**Comment by seesharper** [comment]
We might look into adding an extensibility point for this that makes it possible to sort service registrations container compilation

**Comment by seesharper** [comment]
Services has always been registered in a hash table, so that is probably just success by accident :)  Nice workaround btw 👍

**Comment by feO2x** [comment]
@seesharper: one could generalize the above method to the following one:

```csharp
public static IServiceRegistry RegisterCollection<TCollection, TItem>(this IServiceRegistry container,
                                                                      IReadOnlyList<Type> orderedTypes,
                                                                      Func<IEnumerable<TItem>, TCollection> convertToTargetCollection)
    where TCollection : IEnumerable<TItem>
{
    foreach (var type in orderedTypes)
    {
        container.Register(type);
    }

    return container.Register(f =>
                              {
                                  var orderedInstances = orderedTypes.Select(t => (TItem) f.GetInstance(t));
                                  return convertToTargetCollection(orderedInstances);
                              });
}
```

This method could then be called e.g. like:

```csharp
container.RegisterCollection<ObservableCollection<IFoo>, IFoo>(orderedTypes, items => new ObservableCollection<IFoo>(items));
container.RegisterCollection<IList<IFoo>, IFoo>(orderedTypes, Enumerable.ToList);
container.RegisterCollection<IReadOnlyList<IFoo>, IFoo>(orderedTypes, Enumerable.ToArray);
```

This solution is still missing a possiblity to inject lifetimes when the ordered types are registered. This would require some kind of `ILifetimeFactory`, maybe as an optional parameter.

**How would you structure a LightInject extension that solves this matter?** I had a quick look at [LightInject.Interception](https://github.com/seesharper/LightInject.Interception), but I think you mainly used the `Decorate` method there as an extension point.

**Comment by seesharper** [comment]
Looking into this now, We need this to work with open generic types as well so it's a little bit more complicated :)

**Comment by feO2x** [comment]
I'm currently developing my own DI container for fun and I simply used a `Dictionary<Type, List<Registration>>` - when a type is registered with the container, the corresponding registration is appended to the end of the list. This doesn't solve the problem with generic type definitions, but IMO the container cannot resolve the order properly when different closed constructed generic types are resolved that map to the same generic type definition (i.e. the user has to specify this by explicitly registering an `IEnumerable` of the wanted type, resolving the closed constructed generic types in the correct order).

https://github.com/feO2x/Light.DependencyInjection/blob/badfedd3661e555c91a680e49608f6025023659f/Code/Light.DependencyInjection/DependencyInjectionContainer.cs#L15

**Comment by seesharper** [comment]
Fixed by #404
